import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/header";
import DarkVeil from "./components/DarkVeil";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="fundo" style={{ width: '100%', height: '600px', position: 'relative' }}>
        <DarkVeil />
        </div>
        <Header />
        <br/>
        <br/>
        <div className="content-wrapper">
        {children}
        </div>
      </body>
    </html>
  );
}
